[package]
name = "influxdb3_write"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
data_types = { path = "../data_types" }
influxdb-line-protocol = { path = "../influxdb_line_protocol" }
iox_query = { path = "../iox_query" }
object_store.workspace = true
observability_deps = { path = "../observability_deps" }
schema = { path = "../schema" }
workspace-hack = { version = "0.1", path = "../workspace-hack" }


arrow = { workspace = true }
async-trait = "0.1"
byteorder = "1.3.4"
chrono = "0.4"
crc32fast = "1.2.0"
crossbeam-channel = "0.5.11"
datafusion = { workspace = true }
datafusion_util = { path = "../datafusion_util" }
parking_lot = "0.12.1"
parquet = { workspace = true }
thiserror = "1.0"
tokio = { version = "1.35", features = ["macros", "fs", "io-util", "parking_lot", "rt-multi-thread", "sync", "time"] }
serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0.107"
snap = "1.0.0"
bytes = "1.5.0"
futures-util = "0.3.30"

[dev-dependencies]
arrow_util = { path = "../arrow_util" }
test_helpers = { path = "../test_helpers" }

